ifndef::include-only-once[]
:root-path: ../
include::{root-path}_config.adoc[]
endif::[]
= Protobuffer files

TODO: Add general description.

osi_common.proto::
TODO: Add description.

osi_datarecording.proto::
TODO: Add description.

osi_detectedlane.proto::
TODO: Add description.

osi_detectedobject.proto::
TODO: Add description.

osi_detectedoccupant.proto::
TODO: Add description.

osi_detectedroadmarking.proto::
TODO: Add description.

osi_detectedtrafficlight.proto::
TODO: Add description.

osi_detectedtrafficsign.proto::
TODO: Add description.

osi_environment.proto::
TODO: Add description.

osi_featuredata.proto::
TODO: Add description.

osi_groundtruth.proto::
TODO: Add description.

osi_hostvehicledata.proto::
TODO: Add description.

osi_lane.proto::
TODO: Add description.

osi_logicaldetectiondata.proto::
TODO: Add description.

osi_object.proto::
TODO: Add description.

osi_occupant.proto::
TODO: Add description.

osi_roadmarking.proto::
TODO: Add description.

osi_sensordata.proto::
TODO: Add description.

osi_sensorspecific.proto::
TODO: Add description.

osi_sensorview.proto::
TODO: Add description.

osi_sensorviewconfiguration.proto::
TODO: Add description.

osi_trafficcommand.proto::
TODO: Add description.

osi_trafficlight.proto::
TODO: Add description.

osi_trafficsign.proto::
TODO: Add description.

osi_trafficupdate.proto::
TODO: Add description.
