ifndef::include-only-once[]
:root-path: ../
include::{root-path}_config.adoc[]
endif::[]
= Sensor-view configuration

The sensor view is flexibly defined to provide different kinds of sensor models with an appropriate input.
The sensor-view configuration defines the configuration of a particular sensor view.

The `SensorViewConfiguration` message is used in the initialization phase of a simulation to negotiate the sensor-view configuration for a particular `SensorView` input.
It is also included as a sub-message in `SensorView` messages to indicate that the sensor-view configuration is valid for a particular `SensorView` message.

`SensorViewConfiguration` data has two main applications:

* Enable the environment simulation to provide the necessary input to a sensor model.
* Enable a sensor model to check whether the input matches its requirements.
If the input does not match the requirements, the sensor model may terminate the simulation.

NOTE: `SensorViewConfiguration` data is intended for the automatic configuration of the `SensorView` interface between an environment simulation and sensor model.
The data is not intended to be a mechanism for parametrizing a generic sensor model.

During the initialization phase, there are two sources for `SensorViewConfiguration` data:

. `SensorViewConfiguration` data may be provided by the sensor model to the environment simulation.
In this case, the data describes the input configuration that is requested by the sensor model.
If the sensor model does not provide such data, then the environment simulation will fall back to manual configuration of the sensor view.
+
. `SensorViewConfiguration` data may be provided by the environment simulation.
In response to the request by the sensor model, or based on manual configuration, the environment simulation configures the input and provides a new message that describes the actual configuration.

The configuration requested by the sensor model may differ from the configuration provided by the environment simulation.
This happens when the environment simulation does not support a requested configuration or when the requested configuration is ambiguous.

In response to this difference, the sensor model can either accept this difference and adapt to it, or it can terminate the simulation to indicate that it is not able to accept the difference.

The packaging layer defines the specifics of this auto-negotiation mechanism.

After the initialization phase, the environment simulation provides the actual sensor-view configuration as part of each `SensorView` message.