= Sensor view configuration

The sensor view is flexibly defined to support different kinds of sensor models with appropriate input.
The sensor view configuration defines the configuration of a particular sensor view.

This message is used in the initialization phase of a simulation to negotiate the sensor view configuration for a particular sensor view input.
It is also included as a sub-message in all sensor view messages to indicate the sensor view configuration valid for this particular sensor view message.

Sensor-view-configuration data enables the environment simulation to supply the necessary input to a sensor model.
It further enables a sensor model to check whether the input supplied matches its requirements and expectations and to terminate a simulation if this is not the case.

NOTE: The data is intended for the automatic configuration of the sensor view interface between environment simulation and sensor model.
Sensor-view-configuration data is not intended as a mechanism to parametrize a generic sensor model. 

During the initialization phase, there are two sources for sensor-view-configuration data:

1. Sensor-view-configuration data may be provided by the sensor model to the environment simulation.
+
In this case, the data describes the input configuration that is requested by the sensor model.
If no such data is provided by a sensor model, then the environment simulation will fall back to manual configuration of the sensor view.

2. Sensor-view-configuration data may be provided by the environment simulation.
+
In response to the request by the sensor model, or based on manual configuration, the environment simulation configures the input and provides a new message that describes the actual configuration.

The configuration requested by the sensor model may differ from the configuration provided by the environment simulation.
This happens when the environment simulation does not support a requested configuration or when the requested configuration is ambiguous.

In response to this difference the sensor model can either accept this difference and adapt to it, or it can terminate the simulation to indicate that it is not able to accept the difference.

The specifics of the auto negotiation mechanism are specified in the packaging layer.

After the initialization phase the environment simulation will provide the actual sensor view configuration also as part of each sensor view message.