= Sensor view configuration

Sensor-view-configuration data enables the environment simulation to supply the necessary input to a sensor model.

There are two sources for sensor-view-configuration data:

1. Sensor-view-configuration data may be provided by the environment simulation.
+
NOTE: The data is intended for the automatic configuration of an environment simulation. Sensor-view-configuration data is not intended to provide parameters to a sensor model.

2. Sensor-view-configuration data may be provided by the sensor model to the environment simulation.
+
In this case, the data describes the input configuration that is requested by the sensor model.
In response, the environment simulation configures the input and provides a new message that describes the actual configuration.

The message describing the configuration requested by the sensor model differs from the message describing the configuration provided by the environment simulation.
The configuration requested by the sensor model may differ from the configuration provided by the environment simulation.
This happens when the environment simulation does not support a requested configuration or when the requested configuration is ambiguous.