ifndef::include-only-once[]
:root-path: ../
include::{root-path}_config.adoc[]
endif::[]
= Sensor data

`SensorData` messages imitate the output of real sensors.
They can be generated from `GroundTruth` messages, `SensorView` messages, `FeatureData` messages, or `SensorData` messages.
With the exception of feature data, all information regarding the environment is given with respect to the virtual sensor coordinate system.
Feature data is given with respect to the physical sensor coordinate system.
Sensor data can be used as input for an automated driving function, a sensor model simulating limited perception, or a sensor fusion model.

`SensorData` messages include `FeatureData` messages which contain detected features in the reference frame of a sensor.
`FeatureData` messages are generated from `GroundTruth` messages.
They serve, for example, as an input to sensor models simulating object detection or feature fusion models.

For more details, see xref:gen:structosi3_1_1SensorData.adoc[].