ifndef::include-only-once[]
:root-path: ../
include::{root-path}_config.adoc[]
endif::[]
= Native binary and Human-readable Formats

== Binary .osi Format
Messages are separated by a four-byte, little-endian, unsigned integer specifying the length of each message.

== Human-readable .txth Format
Messages are stored as plain text, separated by newlines.

== Naming Convention
Binary .osi and human-readable .txth files should follow this naming convention:

----
<timestamp>_<type>_<osi-version>_<protobuf-version>_<number-of-frames>_<custom-trace-name>.osi
----

**Types**

`sv`::
Trace file contains `SensorView` messages.

`svc`::
Trace file contains `SensorViewConfiguration` messages.

`gt`::
Trace file contains `GroundTruth` messages.

`hvd`::
Trace file contains `HostVehicleData` messages.

`sd`::
Trace file contains `SensorData` messages.

`tc`::
Trace file contains `TrafficCommand` messages.

`tcu`::
Trace file contains `TrafficCommandUpdate` messages.

`tu`::
Trace file contains `TrafficUpdate` messages.

`mr`::
Trace file contains `MotionRequest` messages.

`su`::
Trace file contains `StreamingUpdate` messages.

**Example**

Given an OSI trace file with the following information:

[#tab-example-osi-trace-file-information]
.Example OSI trace file information
[cols="1,1"]
|===
|Timestamp (ISO 8601) cite:[iso8601]
|20210818T150542Z

|Type
|SensorView

|OSI version
|3.1.2

|Protobuf version
|3.0.0

|Number of frames
|1523

|Custom trace name
|highway
|===

The recommended file name is:

----
20210818T150542Z_sv_312_300_1523_highway.osi
----

NOTE: This naming convention does not apply to .mcap files, they must follow the naming convention described in their section.