= Traffic participant

A traffic participant is an element of the simulated world, which can change its state during simulation time, for example, position and orientation.
A traffic participant represents one of the following:

- A living being.
- A means of transportation for living beings
- A means of transportation for goods
- Any other movable object that may travel the road network

Pedestrians and animals are examples of traffic participants that are living beings.
Vehicles are examples of traffic participants that are means of transportation.
Therefore, the ego vehicle is also a traffic participant.

The following figure shows the interface of a traffic participant.

TODO: Add image of traffic participant interface.

With every simulation step, an OSI traffic participant model receives ground truth data from the environment around itself, the sensor view.
A traffic participant can output its own perceivable state, the traffic update.
Traffic commands influence the behavior of the traffic participant model.
They allow event-based communication towards the traffic participant, that is, at certain simulation steps.
Traffic commands do not necessarily need to come from the environment simulation.
They may come from a separate source, for example, a scenario engine.