= https://github.com/OpenSimulationInterface/open-simulation-interface/releases/tag/v2.0.0[v2.0.0 - OSI Initial Commit]


This is the initial version of the Open Simulation Interface (OSI).

== Overview

OSI is a generic interface for the environmental perception of automated driving functions in virtual scenarios.
It has been primarily conceived to enable easy and straightforward compatibility between automated driving functions and the variety of driving simulation frameworks that are available.
The data description has been derived from the perspective of sensor modeling for automated testing and validation of highly automated driving functions.

== Implementation

OSI primarily contains an object based environment description using the message format of the protocol buffers library, which Google has developed and maintains.

== Detailed description

Top-level interfaces::
OSI consists of two individual top level interfaces for object data: The ``OSI::GroundTruth`` and the ``OSI::SensorData`` interface.
+
* The ``OSI::GroundTruth`` interface provides an exact view of the simulated objects in a global coordinate system.
This message is populated using the internally available data of the used (driving) simulation framework and then published to external subscribers with an exporter plugin.
* The ``OSI::SensorData`` interface describes the objects in the reference frame of a sensor for environmental perception.
It is generated from an ``OSI::GroundTruth`` message and can either be used to directly connect to an automated driving function using ideal simulated data, or it may serve as an input for a sensor model simulating limited perception as a replication of real world sensor behavior.

Low-level interfaces::
+
In addition to the two top-level interfaces, OSI contains an ``OSI::LowLevelData`` message.
This message describes the output of a (physical) model of the measurement process before tracking and object hypothesis.
It does not deal with object data, but may comprise the geometrical influence of 3D simulations, for example, generating Lidar point clouds with a ray-tracer plugin.
This message also supports generic radar reflection lists and will be extended to supporting low-level camera data in the future.
