
name: Antora build trigger

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  trigger_antora:
    name: Trigger antora generator

    runs-on: Ubuntu-latest

    steps:
    - name: Trigger generator
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.MACHINE_USER_PAT }}
        event-type: antora-build-trigger
        repository: OpenSimulationInterface/osi-antora-generator
        client-payload: '{"src": "${{ github.repository }}", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
        